# Changes here will be overwritten by Copier
_commit: 1.0.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: joseph.ware@diamond.ac.uk
author_name: Joseph Ware
component_owner: user:qwe67581
description: TaskGraph implementation of Bluesky plans
distribution_name: bluesky-taskgraph
docker: false
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: bluesky_taskgraph
repo_name: bluesky-taskgraph
